name: dbt CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install dbt-snowflake==1.6.0  # match your local version

    - name: Set up dbt profiles
      run: |
        mkdir -p ~/.dbt
        echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

    - name: dbt seed
      run: dbt seed --project-dir dbt_amazon --target dev

    - name: dbt run
      run: dbt run --project-dir dbt_amazon --target dev

    - name: dbt test
      run: dbt test --project-dir dbt_amazon --target dev